### ISSUE TITLE
very laggy even on expensive vps

### ISSUE THREAD

**Issue by noulalu** [CrabbytheCrab/Crabdiep#3]
im only running to gamemodes with around 10 players in each and its very laggy and all the collisions with shapes and walls are pretty broken

**Comment by CrabbytheCrab** [comment]
It's due to the server I use thats causing the lag(it isn't laggy when locally hosted)

**Comment by noulalu** [comment]
ok thanks, I figured it out it was running on 2 cores instead of 4
